// Tailwind build config for the Dual design. Rebuild styles.css with `npm run build`.
module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "tertiary": "#8b496a",
        "background": "#fbf8ff",
        "on-tertiary-fixed-variant": "#6f3251",
        "surface-bright": "#fbf8ff",
        "tertiary-fixed": "#ffd8e7",
        "on-tertiary-fixed": "#3a0525",
        "on-primary-fixed-variant": "#5d4200",
        "surface-dim": "#dad9e6",
        "surface-variant": "#e3e1ee",
        "on-primary-container": "#0a1f44",
        "on-surface-variant": "#4e4637",
        "secondary-fixed": "#dee1ff",
        "on-secondary-fixed": "#001159",
        "on-secondary-fixed-variant": "#263ca1",
        "surface-tint": "#7b5900",
        "tertiary-fixed-dim": "#ffafd3",
        "surface-container-high": "#e8e7f4",
        "primary-container": "#c2f0ff",
        "primary": "#184E79",
        "on-secondary": "#ffffff",
        "on-background": "#1a1b24",
        "surface-container-low": "#f4f2ff",
        "primary-fixed-dim": "#efbf60",
        "surface-container": "#eeecfa",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#804060",
        "secondary-container": "#8397ff",
        "tertiary-container": "#ffb6d6",
        "outline-variant": "#d2c5b1",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4156ba",
        "error": "#ba1a1a",
        "primary-fixed": "#ffdea4",
        "surface-container-highest": "#e3e1ee",
        "on-secondary-container": "#0c288f",
        "outline": "#665d4e",
        "inverse-surface": "#2f303a",
        "surface": "#fbf8ff",
        "on-surface": "#1a1b24",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#efbf60",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c3ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1effd",
        "on-primary-fixed": "#261900"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "mono": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"],
        "headline-xl": ["Bricolage Grotesque", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-xl-mobile": ["Bricolage Grotesque", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"],
        "headline-lg-mobile": ["Bricolage Grotesque", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Bricolage Grotesque", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"],
        "body-lg": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"],
        "headline-md": ["Bricolage Grotesque", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"],
        "label-sm": ["JetBrains Mono", "ui-monospace", "Menlo", "monospace"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "800" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }]
      }
    }
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")]
};
